services:
  app:
    image: trdockercris/tradewishes:app-${TAG:-main}
    build: 
      context: app
      platforms: 
        - "linux/amd64"
    environment:
      PORT: "7878"
      VITE_WS_URL: "ws://ec2-44-233-138-225.us-west-2.compute.amazonaws.com:8080"
    ports:
      - "7878:7878"
    volumes:
      - ./app/src:/usr/src/app/src

  server:
    image: trdockercris/tradewishes:server-${TAG:-main}
    build: 
      context: server
      platforms: 
        - "linux/amd64"
    ports:
      - "8425:8425"
    volumes:
      - ./server:/usr/src/app
    restart: on-failure
