services:
  app:
    image: trdockercris/tradewishes:app-main
    build: 
      context: app
      platforms: 
        - "linux/amd64"
    environment:
      PORT: "7878"
    ports:
      - "7878:7878"
    volumes:
      - ./app/src:/usr/src/app/src

  server:
    image: trdockercris/tradewishes:server-main
    build: 
      context: server
      platforms: 
        - "linux/amd64"
    ports:
      - "8425:8425"
    volumes:
      - ./server:/usr/src/app
    restart: on-failure
